<?php
namespace tglobally\tg_nomina\controllers;

use gamboamartin\errores\errores;
use PDO;
use stdClass;
use tglobally\template_tg\html;

class controlador_nom_nomina extends \gamboamartin\nomina\controllers\controlador_nom_nomina {

    public function __construct(PDO $link, stdClass $paths_conf = new stdClass()){
        $html_base = new html();
        parent::__construct( link: $link, html: $html_base);
        $this->titulo_lista = 'Nominas';

        $this->params_actions = new stdClass();
        $this->params_actions->modifica = new stdClass();
        $this->params_actions->modifica->im_registro_patronal_id = new stdClass();
        $this->params_actions->modifica->im_registro_patronal_id->cols = 8;

        $this->params_actions->modifica->em_empleado_id = new stdClass();
        $this->params_actions->modifica->em_empleado_id->cols = 12;
    }

    public function lista(bool $header, bool $ws = false): array
    {

        $r_lista = parent::lista(header:false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al ejecutar template',data:  $r_lista, header: $header,ws:$ws);
        }

        $links = $this->registros;

        $registros = $this->modelo->registros(return_obj: true);
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al obtener registros',data:  $registros, header: $header,ws:$ws);
        }

        foreach ($registros as $indice=>$registro){
            foreach($links as $link){

                if((int)$registro->nom_nomina_id  === (int)$link->nom_nomina_id){
                    $registro->razon_social = $registro->em_empleado_nombre.' '. $registro->em_empleado_ap.' ';
                    $registro->razon_social .= $registro->em_empleado_am;
                    $registro->total_cuota_patronal = $link->total_cuota_patronal;
                    $registro->link_genera_xml = $link->link_genera_xml;
                    $registro->link_modifica = $link->link_modifica;
                    $registro->link_elimina_bd = $link->link_elimina_bd;
                }
            }
            $registros[$indice] = $registro;

        }

        $this->registros = $registros;

        return $r_lista;
    }


}
