<?php
namespace tglobally\tg_nomina\controllers;

use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use gamboamartin\template\html;
use html\tg_row_manifiesto_html;
use models\tg_row_manifiesto;
use PDO;
use stdClass;

class controlador_tg_row_manifiesto extends system {

    public array $keys_selects = array();

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){
        $modelo = new tg_row_manifiesto(link: $link);
        $html_ = new tg_row_manifiesto_html(html: $html);
        $obj_link = new links_menu($this->registro_id);
        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Row Manifiesto';
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta(header: false, ws: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta, header: $header,ws:$ws);
        }
        $this->keys_selects['tg_manifiesto_id'] = new stdClass();
        $this->keys_selects['tg_manifiesto_id']->label = 'Manifiesto';

        $this->keys_selects['em_empleado_id'] = new stdClass();
        $this->keys_selects['em_empleado_id']->label = 'Empleado';

        $inputs = (new tg_row_manifiesto_html(html: $this->html_base))->genera_inputs(controler: $this,
            keys_selects: $this->keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar inputs',data:  $inputs);
        }
        return $r_alta;
    }

}
