<?php
namespace tglobally\tg_nomina\controllers;

use gamboamartin\errores\errores;
use gamboamartin\system\links_menu;
use gamboamartin\system\system;
use gamboamartin\template\html;
use html\tg_manifiesto_deduccion_html;
use html\tg_row_manifiesto_html;
use tglobally\tg_nomina\models\tg_manifiesto_deduccion;
use tglobally\tg_nomina\models\tg_row_manifiesto;
use PDO;
use stdClass;

class controlador_tg_manifiesto_deduccion extends system {

    public array|stdClass $keys_selects = array();

    public function __construct(PDO $link, html $html = new \gamboamartin\template_1\html(),
                                stdClass $paths_conf = new stdClass()){
        $modelo = new tg_manifiesto_deduccion(link: $link);
        $html_ = new tg_manifiesto_deduccion_html(html: $html);
        $obj_link = new links_menu(link: $link, registro_id: $this->registro_id);
        parent::__construct(html:$html_, link: $link,modelo:  $modelo, obj_link: $obj_link, paths_conf: $paths_conf);

        $this->titulo_lista = 'Manifiesto Deduccion';
    }

    public function alta(bool $header, bool $ws = false): array|string
    {
        $r_alta =  parent::alta(header: false, ws: false); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al generar template',data:  $r_alta, header: $header,ws:$ws);
        }
        $this->keys_selects['tg_row_manifiesto_id'] = new stdClass();
        $this->keys_selects['tg_row_manifiesto_id']->label = 'Manifiesto';

        $this->keys_selects['nom_par_deduccion_id'] = new stdClass();
        $this->keys_selects['nom_par_deduccion_id']->label = 'Deduccion';

        $inputs = (new tg_manifiesto_deduccion_html(html: $this->html_base))->genera_inputs(controler: $this,
            keys_selects: $this->keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar inputs',data:  $inputs);
        }
        return $r_alta;
    }

    private function base(): array|stdClass
    {
        $r_modifica =  parent::modifica(header: false,ws:  false);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al generar template',data:  $r_modifica);
        }

        if(!array_key_exists(key: 'tg_row_manifiesto_id', array: $this->keys_selects))
            $this->keys_selects['tg_row_manifiesto_id'] = new stdClass();
        $this->keys_selects['tg_row_manifiesto_id']->label = 'Manifiesto';
        $this->keys_selects['tg_row_manifiesto_id']->id_selected = $this->row_upd->tg_row_manifiesto_id;

        if(!array_key_exists(key: 'nom_par_deduccion_id', array: $this->keys_selects))
            $this->keys_selects['nom_par_deduccion_id'] = new stdClass();
        $this->keys_selects['nom_par_deduccion_id']->label = 'Deduccion';
        $this->keys_selects['nom_par_deduccion_id']->id_selected = $this->row_upd->nom_par_deduccion_id;

        $inputs = (new tg_manifiesto_deduccion_html(html: $this->html_base))->genera_inputs(controler: $this,
            keys_selects: $this->keys_selects);
        if(errores::$error){
            return $this->errores->error(mensaje: 'Error al inicializar inputs',data:  $inputs);
        }

        $data = new stdClass();
        $data->template = $r_modifica;
        $data->inputs = $inputs;

        return $data;
    }

    public function modifica(bool $header, bool $ws = false, string $breadcrumbs = '', bool $aplica_form = true,
                             bool $muestra_btn = true): array
    {
        $base = $this->base();
        if(errores::$error){
            return $this->retorno_error(mensaje: 'Error al maquetar datos',data:  $base,
                header: $header,ws:$ws);
        }

        return $base->template;
    }
}
