<?php /** @var \tglobally\tg_nomina\controllers\controlador_tg_manifiesto $controlador */ ?>
<?php

use config\views;

$url_icons = (new views())->url_icons;
?>

<?php include 'templates/tg_manifiesto/lista/secciones.php'; ?>


<style type="text/css">
    @keyframes ldio-kjp6horjcfr {
        0% {
            opacity: 1
        }
        100% {
            opacity: 0
        }
    }

    .ldio-kjp6horjcfr div {
        left: 47px;
        top: 24px;
        position: absolute;
        animation: ldio-kjp6horjcfr linear 1s infinite;
        background: #0a0a0a;
        width: 6px;
        height: 12px;
        border-radius: 3px / 6px;
        transform-origin: 3px 26px;
    }

    .ldio-kjp6horjcfr div:nth-child(1) {
        transform: rotate(0deg);
        animation-delay: -0.9166666666666666s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(2) {
        transform: rotate(30deg);
        animation-delay: -0.8333333333333334s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(3) {
        transform: rotate(60deg);
        animation-delay: -0.75s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(4) {
        transform: rotate(90deg);
        animation-delay: -0.6666666666666666s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(5) {
        transform: rotate(120deg);
        animation-delay: -0.5833333333333334s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(6) {
        transform: rotate(150deg);
        animation-delay: -0.5s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(7) {
        transform: rotate(180deg);
        animation-delay: -0.4166666666666667s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(8) {
        transform: rotate(210deg);
        animation-delay: -0.3333333333333333s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(9) {
        transform: rotate(240deg);
        animation-delay: -0.25s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(10) {
        transform: rotate(270deg);
        animation-delay: -0.16666666666666666s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(11) {
        transform: rotate(300deg);
        animation-delay: -0.08333333333333333s;
        background: #0a0a0a;
    }

    .ldio-kjp6horjcfr div:nth-child(12) {
        transform: rotate(330deg);
        animation-delay: 0s;
        background: #0a0a0a;
    }

    .loadingio-spinner-spinner-fbpis5xeagh {
        width: 75px;
        height: 75px;
        display: inline-block;
        overflow: hidden;
        margin: 0 auto;
    }

    .ldio-kjp6horjcfr {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(0.75);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }

    .ldio-kjp6horjcfr div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */
</style>

<div id="load-table" class="load-table"></div>


<!--<div class="col-md-9 info-lista">
    <div class="col-lg-12 content">
        <h3 style="
font-size: 20px;
font-style: normal;
font-weight: normal;
line-height: 24px;
color: #304463;" >Hola, <?php /*echo $controlador->datos_session_usuario['adm_usuario_user']; */ ?></h3>
        <div class="lista">
            <div class="card">

                <div class="card-body">
                    <div class="cont_tabla_sucursal  col-md-12">
                        <table class="table table-striped datatable">
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
-->

